import difflib
import os
import re
import tempfile
import time

from ddgs import DDGS
import feedparser
import requests
import telebot

from database import (
    init_db,
    news_exists,
    save_news,
    update_news_status,
    save_error,
    image_exists,
    save_image,
    mark_image_used,
)


TOKEN = os.environ.get("TOKEN")
CHANNEL_ID = "-1004423088204"
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")

RSS_URL = "https://rss.app/feeds/sbl4f7OUFIrh9Wsk.xml"

bot = telebot.TeleBot(TOKEN)

NAMES_DICT = {
    "Mason Marchment": "Мэйсон Марчмент",
    "J.J. Peterka": "Дж. Дж. Петерка",
    "JJ Peterka": "Дж. Дж. Петерка",
    "Zach Werenski": "Зак Веренски",
    "Morgan Rielly": "Морган Райлли",
    "Darnell Nurse": "Дарнелл Нерс",
    "Jacob Trouba": "Джейкоб Троуба",
    "Nick Jensen": "Ник Йенсен",
    "Connor Hellebuyck": "Коннор Хеллебайк",
    "Pat Verbeek": "Пэт Вербик",
    "Carson Carels": "Карсон Карелс",
    "Alberts Smits": "Альберт Шмидт",
    "Claude Giroux": "Клод Жиру",
    "Connor Bedard": "Коннор Бедард",
    "Leo Carlsson": "Лео Карлссон",
    "Jake DeBrusk": "Джейк Дебраск",
    "Barrett Hayton": "Барретт Хэйтон",
    "Adin Hill": "Адин Хилл",
    "Kelly McCrimmon": "Келли МакКриммон",
    "Carter Hart": "Картер Харт",
    "Elliotte Friedman": "Эллиотт Фридман",
    "Frank Seravalli": "Фрэнк Серавалли",
}


def escape_html(text):
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def is_duplicate(new_text, existing_texts, threshold=0.8):
    for text in existing_texts:
        similarity = difflib.SequenceMatcher(
            None,
            new_text,
            text,
        ).ratio()

        if similarity > threshold:
            return True

    return False


def clean_raw_rss_text(raw_text):
    if not raw_text:
        return ""

    text = re.sub(r"<[^>]+>", "", raw_text)
    text = re.sub(
        r"view original|generated by rss\.app",
        "",
        text,
        flags=re.IGNORECASE,
    )

    return text.strip()


def clean_bot_hallucinations(text):
    if not text:
        return text

    chat_triggers = [
        "я понял задачу",
        "понял задачу",
        "давайте ваш текст",
        "вот ваш перевод",
        "конечно, вот",
        "адаптированный пост",
    ]

    if any(trigger in text.lower() for trigger in chat_triggers):
        print(
            "⚠️ Обнаружен пустой диалог нейросети вместо новости. "
            "Блокируем."
        )
        return ""

    replacements = {
        "гендир": "генеральный менеджер",
        "дженерал менеджер": "генеральный менеджер",
        "сработать сделка": "провернуть сделку",
    }

    for bad_word, good_word in replacements.items():
        text = re.sub(
            r"\b" + re.escape(bad_word) + r"\b",
            good_word,
            text,
            flags=re.IGNORECASE,
        )

    return text


def get_entry_id(entry):
    return (
        getattr(entry, "id", None)
        or getattr(entry, "guid", None)
        or getattr(entry, "link", None)
        or clean_raw_rss_text(getattr(entry, "title", ""))
    )


def download_image(query):
    clean_query = (
        f"{query} "
        "-getty -alamy -shutterstock -stock "
        "-watermark -ai -generated -midjourney "
        "-dalle -art -render -drawing -illustration"
    )

    headers = {
        "User-Agent": (
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
            "AppleWebKit/537.36 "
            "(KHTML, like Gecko) "
            "Chrome/122.0.0.0 Safari/537.36"
        )
    }

    bad_url_words = [
        "alamy",
        "getty",
        "shutterstock",
        "depositphotos",
        "stock",
        "dreamstime",
        "vector",
        "illustration",
    ]

    try:
        print(f"🖼️ Поиск изображения: {query}")

        with DDGS() as ddgs:
            results = list(
                ddgs.images(
                    query=clean_query,
                    max_results=30,
                    layout="Wide",
                    size="Large",
                )
            )

            print(f"Получено результатов изображений: {len(results)}")

            for res in results:
                img_url = res.get("image")

                if not img_url:
                    continue

                if image_exists(img_url):
                    print("⚠️ Изображение уже использовалось. Пропускаем.")
                    continue

                if any(
                    bad_word in img_url.lower()
                    for bad_word in bad_url_words
                ):
                    continue

                try:
                    response = requests.get(
                        img_url,
                        headers=headers,
                        timeout=10,
                    )

                    if response.status_code != 200:
                        continue

                    content_type = response.headers.get(
                        "Content-Type",
                        "",
                    ).lower()

                    if not content_type.startswith("image/"):
                        print(
                            f"⚠️ URL не является изображением: "
                            f"{content_type}"
                        )
                        continue

                    if len(response.content) < 5000:
                        print("⚠️ Изображение слишком маленькое. Пропускаем.")
                        continue

                    extension = ".jpg"

                    if "png" in content_type:
                        extension = ".png"
                    elif "webp" in content_type:
                        extension = ".webp"
                    elif "gif" in content_type:
                        extension = ".gif"

                    temp_file = tempfile.NamedTemporaryFile(
                        delete=False,
                        suffix=extension,
                    )

                    temp_file.write(response.content)
                    temp_file.close()

                    save_image(img_url)
                    mark_image_used(img_url)

                    print(f"✅ Изображение найдено: {img_url}")

                    return temp_file.name

                except Exception as e:
                    print(f"⚠️ Ошибка скачивания изображения: {e}")
                    continue

    except Exception as e:
        print(f"❌ Ошибка поиска картинок: {e}")

    return None


def translate_tweet(raw_text, source_id):
    if not raw_text or not raw_text.strip():
        return None

    clean_text = clean_raw_rss_text(raw_text)

    clean_text_for_ai = (
        clean_text.rsplit(" - ", 1)[0]
        if " - " in clean_text
        else clean_text
    )

    if (
        not clean_text_for_ai.strip()
        or len(clean_text_for_ai.strip()) < 10
    ):
        print(
            f"⚠️ Новость слишком короткая или пустая "
            f"('{clean_text_for_ai}'), отмена запроса к ИИ."
        )

        save_error(
            source_id,
            "AI_VALIDATION_ERROR",
            "RSS text is empty or too short",
        )

        return None

    glossary_lines = [
        f"- {eng} -> {rus}"
        for eng, rus in NAMES_DICT.items()
    ]

    names_glossary = "\n".join(glossary_lines)

    prompt = f"""
Ты — ведущий хоккейный инсайдер и спортивный редактор, пишущий о НХЛ.

Твоя задача — адаптировать сухой английский инсайд в хлёсткий,
живой, профессиональный и грамматически безупречный пост
для русскоязычных фанатов хоккея.

Перед выдачей результата самостоятельно проверь:
- факты;
- имена;
- названия клубов;
- падежи;
- отсутствие выдуманных фактов;
- отсутствие лишних игроков;
- естественность русского языка.

НЕ выводи свой анализ, рассуждения или черновик.

Верни только готовый результат в формате:

[FINAL_POST]
[Имя автора на английском]: [Текст поста]
SEARCH_QUERY: [Имя главного игрока на английском] NHL
[/FINAL_POST]

Если автора нет, начинай сразу с текста поста.

СТРОГИЕ ПРАВИЛА:

1. Передавай ТОЛЬКО ту информацию, которая есть
в исходном тексте. Не додумывай контекст.

2. Пиши на естественном русском языке.

3. Обязательно правильно склоняй имена игроков,
тренеров, менеджеров и названия команд.

4. Не используй неформальные прозвища команд.
Никаких «рыцарей», «дьяволов», «ястребов», «лавин»
и других подобных вариантов.

5. GM -> генеральный менеджер.

6. Offer sheet -> оффер-шит.

7. Waivers -> драфт отказов.

8. Не добавляй игроков, которых нет в оригинале.

9. Не добавляй статистику, даты, причины, оценки
или другую информацию, которой нет в оригинале.

10. Не начинай текст с фраз вроде:
«Вот ваш перевод»,
«Конечно»,
«Я понял задачу»,
«Адаптированный пост» и т.п.

СПРАВОЧНИК ИМЕН:

{names_glossary}

Оригинал для обработки:

"{clean_text_for_ai}"
"""

    if not GEMINI_API_KEY:
        print("❌ Ошибка: Не задана переменная GEMINI_API_KEY")

        save_error(
            source_id,
            "AI_ERROR",
            "GEMINI_API_KEY is not configured",
        )

        return None

    url = (
        "https://generativelanguage.googleapis.com/"
        "v1beta/models/gemini-2.5-flash:generateContent"
        f"?key={GEMINI_API_KEY}"
    )

    headers = {
        "Content-Type": "application/json",
    }

    payload = {
        "contents": [
            {
                "parts": [
                    {
                        "text": prompt,
                    }
                ]
            }
        ],
        "generationConfig": {
            "temperature": 0.1,
        },
    }

    try:
        print("🤖 Отправка новости в Gemini...")

        response = requests.post(
            url,
            headers=headers,
            json=payload,
            timeout=20,
        )

        if response.status_code != 200:
            print(
                f"⚠️ Gemini 2.5 Flash вернул "
                f"{response.status_code}. Пробуем резервную модель."
            )

            fallback_url = (
                "https://generativelanguage.googleapis.com/"
                "v1beta/models/gemini-1.5-flash:generateContent"
                f"?key={GEMINI_API_KEY}"
            )

            response = requests.post(
                fallback_url,
                headers=headers,
                json=payload,
                timeout=20,
            )

        if response.status_code != 200:
            error_text = response.text[:1000]

            print(
                f"❌ Ошибка ответа Gemini API "
                f"({response.status_code}): {error_text}"
            )

            save_error(
                source_id,
                "AI_ERROR",
                f"HTTP {response.status_code}: {error_text}",
            )

            return None

        data = response.json()

        candidates = data.get("candidates", [])

        if not candidates:
            print("❌ Gemini не вернул candidates.")

            save_error(
                source_id,
                "AI_ERROR",
                "Gemini response contains no candidates",
            )

            return None

        parts = candidates[0].get(
            "content",
            {},
        ).get(
            "parts",
            [],
        )

        if not parts:
            print("❌ Gemini не вернул parts.")

            save_error(
                source_id,
                "AI_ERROR",
                "Gemini response contains no parts",
            )

            return None

        ai_text = parts[0].get("text", "").strip()

        if not ai_text:
            print("❌ Gemini вернул пустой текст.")

            save_error(
                source_id,
                "AI_ERROR",
                "Gemini returned empty text",
            )

            return None

        if "[FINAL_POST]" in ai_text and "[/FINAL_POST]" in ai_text:
            ai_text = (
                ai_text.split("[FINAL_POST]", 1)[1]
                .split("[/FINAL_POST]", 1)[0]
                .strip()
            )

        ai_text = (
            ai_text
            .replace("**", "")
            .replace("«", "")
            .replace("»", "")
            .strip()
        )

        if not ai_text:
            print("❌ После очистки ответ Gemini оказался пустым.")

            save_error(
                source_id,
                "AI_VALIDATION_ERROR",
                "Gemini output became empty after cleaning",
            )

            return None

        return ai_text

    except Exception as e:
        print(f"❌ Ошибка вызова Gemini: {e}")

        save_error(
            source_id,
            "AI_ERROR",
            str(e),
        )

        return None


def parse_ai_response(raw_response):
    if not raw_response:
        return None, None

    query_part = "NHL match action"
    post_text = raw_response.strip()

    if "SEARCH_QUERY:" in raw_response:
        idx = raw_response.rfind("SEARCH_QUERY:")

        post_text = raw_response[:idx].strip()

        query_part = (
            raw_response[idx:]
            .replace("SEARCH_QUERY:", "", 1)
            .strip()
        )

    post_text = clean_bot_hallucinations(post_text)

    if not post_text.strip():
        return None, None

    if "SEARCH_QUERY:" in query_part:
        query_part = (
            query_part
            .replace("SEARCH_QUERY:", "")
            .strip()
        )

    if not query_part:
        query_part = "NHL match action"

    return post_text.strip(), query_part.strip()


def send_telegram_with_retry(final_post, image_path=None):
    last_error = None

    for attempt in range(1, 4):
        try:
            print(
                f"📨 Отправка в Telegram. "
                f"Попытка {attempt}/3..."
            )

            if image_path and os.path.exists(image_path):
                with open(image_path, "rb") as photo:
                    message = bot.send_photo(
                        CHANNEL_ID,
                        photo,
                        caption=final_post,
                        parse_mode="HTML",
                    )

                return message

            message = bot.send_message(
                CHANNEL_ID,
                final_post,
                parse_mode="HTML",
            )

            return message

        except Exception as e:
            last_error = e

            print(
                f"⚠️ Ошибка Telegram "
                f"на попытке {attempt}/3: {e}"
            )

            if attempt < 3:
                time.sleep(5 * attempt)

    raise last_error


def process_entry(entry, already_processed_texts):
    entry_id = get_entry_id(entry)

    title = (
        getattr(entry, "title", "").strip()
        or getattr(entry, "summary", "").strip()
    )

    title = clean_raw_rss_text(title)

    entry_link = getattr(entry, "link", "")

    if not entry_id:
        print("⚠️ Пропускаем новость без ID.")
        return False

    if not title:
        print(f"⚠️ Пропускаем новость без заголовка: {entry_id}")
        return False

    if news_exists(entry_id):
        print(f"↩️ Новость уже есть в базе: {title}")
        return False

    print("")
    print("=" * 70)
    print(f"📰 Новость: {title}")
    print(f"🆔 ID: {entry_id}")
    print("=" * 70)

    save_news(
        source_id=entry_id,
        title=title,
        url=entry_link,
        status="processing",
    )

    raw_response = translate_tweet(
        title,
        entry_id,
    )

    if not raw_response:
        update_news_status(
            entry_id,
            "ai_failed",
        )

        print(
            "❌ Не удалось получить корректный текст "
            "от Gemini."
        )

        return False

    post_text, search_query = parse_ai_response(
        raw_response
    )

    if not post_text:
        update_news_status(
            entry_id,
            "ai_validation_failed",
        )

        save_error(
            entry_id,
            "AI_VALIDATION_ERROR",
            "Post text is empty after parsing",
        )

        print("❌ AI-ответ не прошёл проверку.")

        return False

    if is_duplicate(
        post_text,
        already_processed_texts,
        threshold=0.8,
    ):
        update_news_status(
            entry_id,
            "duplicate",
        )

        save_error(
            entry_id,
            "DUPLICATE",
            "Post is too similar to another post in current run",
        )

        print(
            "↩️ Похожий пост уже обрабатывался "
            "в текущем запуске. Пропускаем."
        )

        return False

    already_processed_texts.append(post_text)

    if ": " in post_text:
        author, text_content = post_text.split(
            ": ",
            1,
        )

        author = (
            author
            .replace("Источник", "")
            .strip()
        )

        if author:
            final_post = (
                f"<b>{escape_html(author)}</b>\n"
                f"{escape_html(text_content)}"
            )
        else:
            final_post = escape_html(text_content)

    else:
        final_post = escape_html(post_text)

    print(f"🔎 Поисковый запрос для изображения: {search_query}")

    image_path = download_image(search_query)

    if not image_path:
        print(
            "⚠️ По основному запросу изображение "
            "не найдено. Используем запасной запрос."
        )

        image_path = download_image(
            "NHL ice hockey match action"
        )

    try:
        telegram_message = send_telegram_with_retry(
            final_post,
            image_path,
        )

        update_news_status(
            entry_id,
            "published",
            published_at=__import__("datetime")
            .datetime.now(
                __import__("datetime").timezone.utc
            ).isoformat(),
            telegram_message_id=getattr(
                telegram_message,
                "message_id",
                None,
            ),
        )

        print(
            f"✅ Новость успешно опубликована в Telegram: "
            f"{title}"
        )

        return True

    except Exception as e:
        print(
            f"❌ Не удалось отправить новость в Telegram: "
            f"{e}"
        )

        update_news_status(
            entry_id,
            "telegram_failed",
        )

        save_error(
            entry_id,
            "TELEGRAM_ERROR",
            str(e),
        )

        return False

    finally:
        if image_path and os.path.exists(image_path):
            try:
                os.remove(image_path)
            except Exception as e:
                print(
                    f"⚠️ Не удалось удалить временное изображение: "
                    f"{e}"
                )


def main():
    init_db()

    if not TOKEN:
        print("❌ Не задана переменная TOKEN.")
        return

    if not GEMINI_API_KEY:
        print("❌ Не задана переменная GEMINI_API_KEY.")
        return

    headers = {
        "User-Agent": (
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
            "AppleWebKit/537.36 "
            "(KHTML, like Gecko) "
            "Chrome/122.0.0.0 Safari/537.36"
        )
    }

    feed = None

    try:
        print(f"Загрузка RSS: {RSS_URL}...")

        response = requests.get(
            RSS_URL,
            headers=headers,
            timeout=15,
        )

        if response.status_code == 200:
            parsed = feedparser.parse(
                response.content
            )

            if parsed.entries:
                feed = parsed

        else:
            error_message = (
                f"RSS вернул HTTP {response.status_code}"
            )

            print(f"❌ {error_message}")

            save_error(
                None,
                "RSS_ERROR",
                error_message,
            )

    except Exception as e:
        print(f"❌ Ошибка загрузки RSS: {e}")

        save_error(
            None,
            "RSS_ERROR",
            str(e),
        )

    if not feed or not feed.entries:
        print(
            "❌ Не удалось получить новости из RSS-потока."
        )
        return

    print(
        f"Получено записей RSS: {len(feed.entries)}"
    )

    new_entries = []

    for entry in reversed(feed.entries[:30]):
        entry_id = get_entry_id(entry)

        title = (
            getattr(entry, "title", "").strip()
            or getattr(entry, "summary", "").strip()
        )

        clean_title = clean_raw_rss_text(title)

        if not entry_id or not clean_title:
            continue

        if news_exists(entry_id):
            continue

        new_entries.append(entry)

    if not new_entries:
        print("Новых постов нет.")
        return

    print(
        f"Найдено новых новостей для обработки: "
        f"{len(new_entries)}"
    )

    already_processed_texts = []

    success_count = 0
    failed_count = 0

    for entry in new_entries:
        try:
            success = process_entry(
                entry,
                already_processed_texts,
            )

            if success:
                success_count += 1
            else:
                failed_count += 1

        except Exception as e:
            entry_id = get_entry_id(entry)

            print(
                f"❌ Критическая ошибка обработки "
                f"новости {entry_id}: {e}"
            )

            save_error(
                entry_id,
                "PROCESSING_ERROR",
                str(e),
            )

            update_news_status(
                entry_id,
                "processing_failed",
            )

            failed_count += 1

    print("")
    print("=" * 70)
    print("ИТОГ ЗАПУСКА")
    print(f"Успешно опубликовано: {success_count}")
    print(f"Ошибок/пропущено: {failed_count}")
    print("=" * 70)


if __name__ == "__main__":
    main()
