import difflib
import os
import re
import time
from collections import defaultdict
from ddgs import DDGS
import feedparser
import requests
import telebot

TOKEN = os.environ.get("TOKEN")
CHANNEL_ID = "-1004423088204"

# Ключи для нейросетей
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")
OPENROUTER_API_KEY = os.environ.get("OPENROUTER_API_KEY")
HF_TOKEN = os.environ.get("HF_TOKEN")

RSS_URL = "https://rss.app/feeds/sbl4f7OUFIrh9Wsk.xml"

bot = telebot.TeleBot(TOKEN)
HISTORY_FILE = "history.txt"
IMAGE_HISTORY_FILE = "image_history.txt"

NAMES_DICT = {
    "Mason Marchment": "Мэйсон Марчмент",
    "J.J. Peterka": "Дж. Дж. Петерка",
    "JJ Peterka": "Дж. Дж. Петерка",
    "Zach Werenski": "Зак Веренски",
    "Morgan Rielly": "Морган Райлли",
    "Darnell Nurse": "Дарнелл Нерс",
    "Jacob Trouba": "Джейкоб Троуба",
    "Nick Jensen": "Ник Йенсен",
    "Connor Hellebuyck": "Коннор Хеллебайк",
    "Pat Verbeek": "Пэт Вербик",
    "Carson Carels": "Карсон Карелс",
    "Alberts Smits": "Альберт Шмидт",
    "Claude Giroux": "Клод Жиру",
    "Connor Bedard": "Коннор Бедард",
    "Leo Carlsson": "Лео Карлссон",
    "Jake DeBrusk": "Джейк Дебраск",
    "Barrett Hayton": "Барретт Хэйтон",
    "Adin Hill": "Адин Хилл",
    "Kelly McCrimmon": "Келли МакКриммон",
    "Carter Hart": "Картер Харт",
    "Elliotte Friedman": "Эллиотт Фридман",
    "Frank Seravalli": "Фрэнк Серавалли",
}


def get_history():
    if not os.path.exists(HISTORY_FILE):
        return set()
    with open(HISTORY_FILE, "r", encoding="utf-8") as f:
        return set(line.strip() for line in f if line.strip())


def add_to_history(title):
    with open(HISTORY_FILE, "a", encoding="utf-8") as f:
        f.write(title + "\n")


def get_image_history():
    if not os.path.exists(IMAGE_HISTORY_FILE):
        return set()
    with open(IMAGE_HISTORY_FILE, "r", encoding="utf-8") as f:
        return set(line.strip() for line in f if line.strip())


def add_to_image_history(url):
    with open(IMAGE_HISTORY_FILE, "a", encoding="utf-8") as f:
        f.write(url + "\n")


def escape_html(text):
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def is_duplicate(new_text, existing_texts):
    for text in existing_texts:
        similarity = difflib.SequenceMatcher(None, new_text, text).ratio()
        if similarity > 0.8:
            return True
    return False


def clean_raw_rss_text(raw_text):
    if not raw_text:
        return ""
    text = re.sub(r"<[^>]+>", "", raw_text)
    text = re.sub(r"view original|generated by rss\.app", "", text, flags=re.IGNORECASE)
    return text.strip()


def clean_bot_hallucinations(text):
    if not text:
        return text

    chat_triggers = [
        "я понял задачу",
        "понял задачу",
        "давайте ваш текст",
        "вот ваш перевод",
        "конечно, вот",
        "адаптированный пост",
    ]
    if any(trigger in text.lower() for trigger in chat_triggers):
        print("⚠️ Обнаружен пустой диалог нейросети вместо новости. Блокируем.")
        return ""

    replacements = {
        "гендир": "генеральный менеджер",
        "дженерал менеджер": "генеральный менеджер",
        "сработать сделка": "провернуть сделку",
    }
    for bad_word, good_word in replacements.items():
        text = re.sub(
            r"\b" + re.escape(bad_word) + r"\b", good_word, text, flags=re.IGNORECASE
        )
    return text


def parse_final_post_text(ai_text):
    """Извлекает блок [FINAL_POST] и очищает его от лишних символов и тегов мыслей."""
    if not ai_text:
        return None

    # Отрезаем размышления DeepSeek-R1, если они присутствуют
    ai_text = re.sub(r"<think>.*?</think>", "", ai_text, flags=re.DOTALL)

    if "[FINAL_POST]" in ai_text and "[/FINAL_POST]" in ai_text:
        ai_text = ai_text.split("[FINAL_POST]")[1].split("[/FINAL_POST]")[0].strip()

    cleaned = (
        ai_text.replace("**", "")
        .replace('"', "")
        .replace("«", "")
        .replace("»", "")
        .strip()
    )
    return cleaned if len(cleaned) > 10 else None


# --- БЛОКИ ОБРАЩЕНИЯ К НЕЙРОСЕТЯМ С ПОВТОРАМИ (5 РАЗ ПО 5 СЕКУНД) ---


def request_gemini(prompt):
    if not GEMINI_API_KEY:
        return None

    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key={GEMINI_API_KEY}"
    payload = {
        "contents": [{"parts": [{"text": prompt}]}],
        "generationConfig": {"temperature": 0.1},
    }
    headers = {"Content-Type": "application/json"}

    for attempt in range(1, 6):
        try:
            print(f"Попытка Gemini {attempt}/5...")
            response = requests.post(url, headers=headers, json=payload, timeout=20)
            if response.status_code == 200:
                data = response.json()
                candidates = data.get("candidates", [])
                if candidates:
                    parts = candidates[0].get("content", {}).get("parts", [])
                    if parts:
                        text = parts[0].get("text", "")
                        result = parse_final_post_text(text)
                        if result:
                            return result
            else:
                print(f"⚠️ Gemini вернул код {response.status_code}: {response.text[:100]}")
        except Exception as e:
            print(f"⚠️ Ошибка запроса к Gemini: {e}")

        if attempt < 5:
            time.sleep(5)

    return None


def request_openrouter(prompt):
    if not OPENROUTER_API_KEY:
        return None

    url = "https://openrouter.ai/api/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {OPENROUTER_API_KEY}",
        "Content-Type": "application/json",
    }
    payload = {
        "model": "google/gemma-4-26b-a4b-it:free",
        "messages": [{"role": "user", "content": prompt}],
        "temperature": 0.1,
    }

    for attempt in range(1, 6):
        try:
            print(f"Попытка OpenRouter {attempt}/5...")
            response = requests.post(url, headers=headers, json=payload, timeout=25)
            if response.status_code == 200:
                data = response.json()
                choices = data.get("choices", [])
                if choices:
                    raw_text = choices[0].get("message", {}).get("content", "")
                    result = parse_final_post_text(raw_text)
                    if result:
                        return result
            else:
                print(f"⚠️ OpenRouter вернул код {response.status_code}: {response.text[:100]}")
        except Exception as e:
            print(f"⚠️ Ошибка запроса к OpenRouter: {e}")

        if attempt < 5:
            time.sleep(5)

    return None


def request_huggingface(prompt):
    if not HF_TOKEN:
        return None

    url = "https://router.huggingface.co/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {HF_TOKEN}",
        "Content-Type": "application/json",
    }
    payload = {
        "model": "deepseek-ai/DeepSeek-R1:novita",
        "messages": [{"role": "user", "content": prompt}],
        "temperature": 0.1,
    }

    for attempt in range(1, 6):
        try:
            print(f"Попытка Hugging Face {attempt}/5...")
            response = requests.post(url, headers=headers, json=payload, timeout=30)
            if response.status_code == 200:
                data = response.json()
                choices = data.get("choices", [])
                if choices:
                    raw_text = choices[0].get("message", {}).get("content", "")
                    result = parse_final_post_text(raw_text)
                    if result:
                        return result
            else:
                print(f"⚠️ Hugging Face вернул код {response.status_code}: {response.text[:100]}")
        except Exception as e:
            print(f"⚠️ Ошибка запроса к Hugging Face: {e}")

        if attempt < 5:
            time.sleep(5)

    return None


def translate_tweet(raw_text):
    if not raw_text or not raw_text.strip():
        return None

    clean_text = clean_raw_rss_text(raw_text)
    clean_text_for_ai = (
        clean_text.rsplit(" - ", 1)[0] if " - " in clean_text else clean_text
    )

    if not clean_text_for_ai.strip() or len(clean_text_for_ai.strip()) < 10:
        print(
            f"⚠️ Новость слишком короткая или пустая ('{clean_text_for_ai}'), отмена запроса к ИИ."
        )
        return None

    glossary_lines = [f"- {eng} -> {rus}" for eng, rus in NAMES_DICT.items()]
    names_glossary = "\n".join(glossary_lines)

    prompt = f"""
Ты — ведущий хоккейный инсайдер и спортивный редактор, пишущий о НХЛ. Твоя задача — адаптировать сухой английский инсайд (твит) в хлёсткий, живой, профессиональный и грамматически безупречный пост для русскоязычных фанатов хоккея.

ВЫПОЛНИ АНАЛИЗ И САМОПРОВЕРКУ ШАГ ЗА ШАГОМ, ЗАТЕМ ВЫДАЙ ОТВЕТ В СЛЕДУЮЩЕЙ СТРУКТУРЕ:

[АНАЛИЗ ОРИГИНАЛА]
1. Выпиши все имена игроков, тренеров, менеджеров и названия клубов из оригинала.

[ЧЕРНОВИК И ПРОВЕРКА]
1. Напиши предварительный вариант перевода.
2. Убедись, что ты НЕ добавил лишних игроков или фактов «из головы» (если в тексте только Hill и Hart, никаких других вратарей быть не должно).
3. Проверь падежи и окончания имен. Падеж должен идеально соответствовать контексту русского языка (например: «инсайд от Эллиотта Фридмана», «обмен Зак Веренски» -> «обмен Зака Веренски»).

[FINAL_POST]
Внутри этого блока должен быть ТОЛЬКО готовый новостной пост и в самом конце строка SEARCH_QUERY. Никаких других комментариев!
[/FINAL_POST]

СТРОГИЕ ПРАВИЛА ДЛЯ БЛОКА [FINAL_POST]:
1. ЖЕСТКАЯ ФАКТОЛОГИЯ: Передавай ТОЛЬКО ту информацию, которая есть в тексте. Не додумывай контекст.
2. ГРАМОТНОСТЬ И ПАДЕЖИ: Пиши на естественном русском языке. Обязательно правильно склоняй имена игроков и названия команд/городов согласно правилам русского языка (например: «в Нью-Джерси», «у Анахайма», «с Мэйсоном Марчментом»). 
3. ЗАПРЕТ НА ПРОЗВИЩА: Категорически запрещено использовать неформальные прозвища команд (никаких "рыцарей", "дьяволов", "ястребов", "лавин"). Вместо них пиши официальные названия городов или клубов: Вегас, Нью-Джерси, Чикаго, Колорадо.
4. ТЕРМИНОЛОГИЯ: GM -> генеральный менеджер, Offer sheet -> оффер-шит, Waivers -> драфт отказов.
5. АВТОРСТВО: Формат первой строки строго такой: [Имя Автора по-английски]: [Текст поста]. Если автора нет, просто начни с текста.
6. СПРАВОЧНИК ИМЕН (Используй эти русские соответствия как базу в именительном падеже и правильно склоняй их под контекст предложения):
{names_glossary}

7. ФИНАЛ: В самой последней строке внутри тегов [FINAL_POST] напиши строго: SEARCH_QUERY: [Имя главного игрока на английском] NHL

Оригинал для обработки: "{clean_text_for_ai}"
"""

    # 1. Приоритет: Google Gemini
    result = request_gemini(prompt)
    if result:
        return result

    # 2. Второй резерв: OpenRouter
    print("⚠️ Gemini не ответил за 5 попыток. Переключаемся на OpenRouter...")
    result = request_openrouter(prompt)
    if result:
        return result

    # 3. Третий резерв: Hugging Face
    print("⚠️ OpenRouter не ответил за 5 попыток. Переключаемся на Hugging Face...")
    result = request_huggingface(prompt)
    if result:
        return result

    print("❌ Ни одна из трех нейросетей не смогла обработать пост.")
    return None


def download_image(query):
    clean_query = f"{query} -getty -alamy -shutterstock -stock -watermark -ai -generated -midjourney -dalle -art -render -drawing -illustration"
    time.sleep(2)

    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
    }
    bad_url_words = [
        "alamy",
        "getty",
        "shutterstock",
        "depositphotos",
        "stock",
        "dreamstime",
        "vector",
        "illustration",
    ]
    image_history = get_image_history()

    try:
        with DDGS() as ddgs:
            results = list(
                ddgs.images(
                    query=clean_query, max_results=30, layout="Wide", size="Large"
                )
            )

            for res in results:
                img_url = res.get("image")
                if not img_url or img_url in image_history:
                    continue
                if any(bad in img_url.lower() for bad in bad_url_words):
                    continue

                try:
                    response = requests.get(img_url, headers=headers, timeout=10)
                    if response.status_code == 200:
                        add_to_image_history(img_url)
                        with open("temp.png", "wb") as handler:
                            handler.write(response.content)
                        return "temp.png"
                except Exception:
                    continue
    except Exception as e:
        print(f"Ошибка поиска картинок: {e}")
    return None


def alternate_posts(posts):
    if not posts:
        return []
    grouped = defaultdict(list)
    for p in posts:
        grouped[p["query"]].append(p)

    sorted_posts = []
    while any(grouped.values()):
        for key in list(grouped.keys()):
            if grouped[key]:
                sorted_posts.append(grouped[key].pop(0))
            else:
                del grouped[key]
    return sorted_posts


def main():
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
    }

    feed = None
    try:
        print(f"Загрузка RSS: {RSS_URL}...")
        response = requests.get(RSS_URL, headers=headers, timeout=15)
        if response.status_code == 200:
            parsed = feedparser.parse(response.content)
            if parsed.entries:
                feed = parsed
    except Exception as e:
        print(f"❌ Ошибка загрузки RSS: {e}")

    if not feed or not feed.entries:
        print("❌ Не удалось получить новости из RSS-потока.")
        return

    history = get_history()

    new_entries = []
    for entry in reversed(feed.entries[:10]):
        entry_id = getattr(entry, "id", None) or getattr(entry, "link", None)
        title = (
            getattr(entry, "title", "").strip()
            or getattr(entry, "summary", "").strip()
        )
        clean_title = clean_raw_rss_text(title)

        check_val = entry_id if entry_id else clean_title

        if clean_title and check_val not in history and clean_title not in history:
            entry.title = clean_title
            entry.history_id = check_val
            new_entries.append(entry)

    if not new_entries:
        print("Новых постов нет.")
        return

    raw_posts_pool = []
    entries_to_save = []

    for entry in new_entries:
        raw_response = translate_tweet(entry.title)
        if raw_response:
            query_part = "NHL match action"
            post_text = raw_response
            if "SEARCH_QUERY:" in raw_response:
                idx = raw_response.rfind("SEARCH_QUERY:")
                post_text = raw_response[:idx].strip()
                query_part = raw_response[idx:].replace("SEARCH_QUERY:", "").strip()

            post_text = clean_bot_hallucinations(post_text)

            if not post_text.strip():
                entries_to_save.append(entry.history_id)
                continue

            if ": " in post_text:
                author, text_content = post_text.split(": ", 1)
                raw_posts_pool.append(
                    {
                        "author": author.replace("Источник", "").strip(),
                        "text": text_content,
                        "query": query_part,
                        "entry_id": entry.history_id,
                    }
                )
            else:
                raw_posts_pool.append(
                    {
                        "author": "",
                        "text": post_text,
                        "query": query_part,
                        "entry_id": entry.history_id,
                    }
                )

    alternated_posts = alternate_posts(raw_posts_pool)

    combined_texts = []
    pure_texts_for_diff = []
    search_queries = []

    for p in alternated_posts:
        if is_duplicate(p["text"], pure_texts_for_diff):
            entries_to_save.append(p["entry_id"])
            continue

        pure_texts_for_diff.append(p["text"])
        if p["author"]:
            formatted_text = (
                f"<b>{escape_html(p['author'])}</b>\n{escape_html(p['text'])}"
            )
        else:
            formatted_text = escape_html(p["text"])

        combined_texts.append(formatted_text)
        search_queries.append(p["query"])
        entries_to_save.append(p["entry_id"])

    if combined_texts:
        final_post = "\n\n".join(combined_texts)
        image_path = None

        for query in search_queries:
            image_path = download_image(query)
            if image_path:
                break

        if not image_path:
            image_path = download_image("NHL ice hockey match action")

        try:
            image_sent = False
            if image_path and os.path.exists(image_path):
                try:
                    with open(image_path, "rb") as photo:
                        if len(final_post) <= 1024:
                            bot.send_photo(
                                CHANNEL_ID,
                                photo,
                                caption=final_post,
                                parse_mode="HTML",
                            )
                        else:
                            bot.send_photo(CHANNEL_ID, photo)
                            bot.send_message(CHANNEL_ID, final_post, parse_mode="HTML")
                    image_sent = True
                except Exception as e:
                    print(f"⚠️ Telegram отклонил файл: {e}")
                finally:
                    if os.path.exists(image_path):
                        os.remove(image_path)

            if not image_sent:
                bot.send_message(CHANNEL_ID, final_post, parse_mode="HTML")

            for item_id in entries_to_save:
                add_to_history(item_id)

        except Exception as e:
            print(f"❌ Ошибка отправки: {e}")


if __name__ == "__main__":
    main()
