name: NHL Feed Watcher
on:
  schedule:
    # 09:00 - 14:00 по МСК (06:00 - 11:00 UTC) -> 1 раз в час
    - cron: '0 6-11 * * *'
    # 14:30 по МСК (11:30 UTC)
    - cron: '30 11 * * *'
    # 15:00 - 02:30 по МСК (12:00 - 23:30 UTC) -> каждые 30 минут
    - cron: '0,30 12-23 * * *'
    # 03:00 - 08:30 по МСК (00:00 - 05:30 UTC) -> каждые 30 минут
    - cron: '0,30 0-5 * * *'
  workflow_dispatch: # Кнопка ручного запуска

permissions:
  actions: write
  contents: read

jobs:
  check_feed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install feedparser

      - name: Check RSS for new entries
        id: check_rss
        run: python check_rss.py

      - name: Trigger NHL News Bot
        if: steps.check_rss.outputs.NEW_NEWS == 'true'
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/main.yml/dispatches \
            -d '{"ref":"main"}'
